## Import relevant libraries


In [1]:
import numpy as np

## Dot product

In [2]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [3]:
np.dot(x,y)

-66

In [6]:
np.dot(y,x)

-66

In [4]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [5]:
np.dot(u,v)

18

## Scalar product

In [7]:
np.dot(5,6)

30

## Scalar*Vector

In [8]:
x

array([ 2,  8, -4])

In [10]:
5*x

array([ 10,  40, -20])

## Scalar*Matrix

In [11]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [12]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

## Matrix*Matrix

In [13]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [14]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])