## import the relevant libraries

In [1]:
import numpy as np

## Addition

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [4]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
m2 = np.array([[9,8],[1,3]])
m2

array([[9, 8],
       [1, 3]])

In [6]:
m1 + m2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Addition of vectors

In [8]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [9]:
v2 = np.array([1,2,3])
v2

array([1, 2, 3])

In [10]:
v1+v2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Exception (addition with a scalar)

In [11]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [12]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [13]:
v1

array([1, 2, 3, 4, 5])

In [14]:
v1 + 1

array([2, 3, 4, 5, 6])