## Import the relevant libraries

In [1]:
import numpy as np

## Scalar

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,2,4])

In [5]:
v

array([5, 2, 4])

## Matrices

In [7]:
m = np.array([[5,12,6],[-3,0,4]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0,  4]])

## Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [12]:
s_array = np.array(5)
s_array

array(5)

In [13]:
type(s_array)

numpy.ndarray

## Data Shape

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

In [16]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

## Creating a column vector

In [17]:
v.reshape(3,1)

array([[5],
       [2],
       [4]])

In [18]:
v.reshape(1,3)

array([[5, 2, 4]])