## Import the relevant libraries

In [1]:
import numpy as np

## Transposing matrices

In [3]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [5]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [6]:
B.T

array([[ 5, -2],
       [ 3,  4]])

## Transposing scalars

In [7]:
s = np.array([5])

In [8]:
s.T

array([5])

## Transposing vectors

In [9]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [10]:
x.T

array([1, 2, 3])

In [12]:
x.shape

(3,)

In [13]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [14]:
x_reshaped.T

array([[1],
       [2],
       [3]])