# Feature scaling with sklearn - Exercise

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. This exercise is very similar to a previous one. This time, however, **please standardize the data**.

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [1]:
import numpy as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data = pd.read_csv("../real_estate_price_size_year.csv")

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [5]:
data.corr()

price      size      year
price  1.000000  0.862983  0.093014
size   0.862983  1.000000 -0.097678
year   0.093014 -0.097678  1.000000

## Create the regression

### Declare the dependent and the independent variables

In [6]:
x = data[['size', 'year']]
y = data['price']

### Scale the inputs

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(x)
scaler.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [10]:
x_scaled = scaler.transform(x)
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

### Regression

In [11]:
reg_scaled = LinearRegression()

In [12]:
reg_scaled.fit(x_scaled, y)
reg_scaled.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

### Find the intercept

In [14]:
reg_scaled.intercept_

292289.4701599997

### Find the coefficients

In [13]:
reg_scaled.coef_

array([67501.57614152, 13724.39708231])

### Calculate the R-squared

In [16]:
r2 = reg_scaled.score(x_scaled, y)
r2

0.7764803683276793

### Calculate the Adjusted R-squared

In [20]:
n = x_scaled.shape[0]
p = x_scaled.shape[1]
x_scaled.shape

(100, 2)

In [21]:
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [22]:
adjusted_r2

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

Answer: The year slightly penalize the r2, they are relatively the same and the year does not contribute any insight to the prediction too much

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Answer: Both values are the same, so the year does not improve the precsion of the prediction

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [33]:
new_data = pd.DataFrame(data=[[750, 2009]], columns=['size','year'])
new_data

size  year
0   750  2009

In [35]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-0.34752816, -0.76509206]])

In [36]:
reg_scaled.predict(new_data_scaled)

array([258330.34465995])

In [49]:
new_data['Predicted Price'] = reg_scaled.predict(new_data_scaled)
new_data

size  year  Predicted Price
0   750  2009     258330.34466

### Calculate the univariate p-values of the variables

In [42]:
from sklearn.feature_selection import f_regression

In [45]:
f_regression(x_scaled, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [46]:
p_values = f_regression(x_scaled, y)[1]

In [58]:
p_values = p_values.round(3)

### Create a summary table with your findings

In [59]:
data_summary = pd.DataFrame(data=[['Bias'],['size'],['year']], columns=['feature'])
data_summary['P-values'] = 0, p_values[0], p_values[1]
data_summary['weights'] = reg_scaled.intercept_, reg_scaled.coef_[0], reg_scaled.coef_[1]
data_summary

feature  P-values        weights
0    Bias     0.000  292289.470160
1    size     0.000   67501.576142
2    year     0.357   13724.397082

Answer: The size is significant to the price and its weight is greatest compare with year and year neither have a great impact on the price nor is significant to the price